### ISSUE TITLE
Chronos V4 not working

### ISSUE THREAD

**Issue by A-r-s-a-n-e** [litetex-oss/mcm-raid-restore#137]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/litetex-oss/mcm-raid-restore/issues) or [closed](https://github.com/litetex-oss/mcm-raid-restore/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

I have built Chronos V4, but for some reason the farm runs every second cycle (instead of raiders every pulse I get raiders every 2 pulses) It seems like the mod might have some sort of bug or issue regarding 10gt spawn cycle of raiders. Is there a way to fix it?

### Additional information

Built it in void world with no blocks nearby, also, there is no double raid bar like there was while using V4 in earlier version. Theoreticaly, the redstone drops should be more than the farm in 1.20 and below, but in 1.21 I get around 12k redstone/h instead of 26k that the farm produced in 1.20

**Comment by litetex** [comment]
Hi, thank you for the question.

So you are essentially describing a bug report in a "question"-type issue.

Could you please fill out a ["bug"-type issue](https://github.com/litetex-oss/mcm-raid-restore/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) with all relevant information (like exact version)?

Also world downloads for comparison would be appreciated :)

**Comment by litetex** [comment]
Inactive
