### ISSUE TITLE
just doesnt work

### ISSUE THREAD

**Issue by CheeseisJuicy** [litetex-oss/mcm-raid-restore#43]

**Comment by litetex** [comment]
Could you please describe what excatly is not working and how it can be reproduced?

**Comment by litetex** [comment]
Here is an example that show that the mod clearly works:

[Showcase](https://github.com/litetex-oss/mcm-raid-restore/assets/40789489/eec2998c-00ad-4f8b-ac66-219fea0d5107)

Please validate that you installed it correctly and if it's still a problem please share a reproduction guide (a video would help).
Feel free to reopen the issue once the criteria are met.
