### ISSUE TITLE
Not stacking like intended

### ISSUE THREAD

**Issue by MythicX3** [litetex-oss/mcm-raid-restore#47]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/litetex-oss/mcm-raid-restore/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/litetex-oss/mcm-raid-restore/issues) or [closed](https://github.com/litetex-oss/mcm-raid-restore/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

1.0.0

### Steps to reproduce the bug

Using this raid farm: https://www.youtube.com/watch?v=D_mmAJtbL1g
After getting bad omen.

### Expected behavior

Working stacking raid farm that works exactly like 1.20

### Actual behavior

It only shoots one raid out, then gives me hero of the village, making me have to get raid omen again making the process WAY slower.

**Comment by litetex** [comment]
Closing due to lack of feedback.
Feel free to reopen the issue once you tried the additional troubleshooting
