### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by codefreak558** [litetex-oss/mcm-raid-restore#49]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/litetex-oss/mcm-raid-restore/issues) or [closed](https://github.com/litetex-oss/mcm-raid-restore/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

I would like to find out if this could get backported to 1.20.4 as I'm using the [No Trial Chamber](https://github.com/misode/no-trial-chambers) Datapack to bring the features to 1.20.4

**Comment by litetex** [comment]
I don't think a backport is possible since the raid changes were implemented with [24w13a](https://minecraft.wiki/w/Java_Edition_24w13a) which was a snapshot for ``1.20.5``. So ``1.20.4`` still works like the versions before - even with ``Experimental Update 1.21`` enabled.

**Comment by codefreak558** [comment]
Okay I have just tested with IanXOFour's stacking raid farm on 1.20.4 with the 1.21 features and it looks like you are correct. I wasn't sure if the new raid mechanics were in 1.20.4
